# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tiktok

# on:
#   schedule:
#   - cron: "*/5 * * * *"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install firebase
        pip install firebase-admin
        sudo apt-get install libegl1\
            libopus0\
            libwoff1\
            libharfbuzz-icu0\
            libgstreamer-plugins-base1.0-0\
            libgstreamer-gl1.0-0\
            libgstreamer-plugins-bad1.0-0\
            libopenjp2-7\
            libwebpdemux2\
            libenchant1c2a\
            libhyphen0\
            libgles2\
            gstreamer1.0-libav
        python -m pip install --upgrade pip
        pip install TikTokApi
        pip3 install cloudinary
        python -m playwright install
        pip install python_jwt
        pip install gcloud
        pip install sseclient
        pip install pycrypto
        pip install requests-toolbelt
        pip install moviepy
        pip install ez_setup
        
    - name: tiktok
      run: |
        python  tiktok.py
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: my-artifact
    #     path: AllVideos/finalVideo.mp4
